@echo off
set "BASE_PATH=C:\Users\sd189\OneDrive\Documentos\Sol_erp"

mkdir "%BASE_PATH%\.github"
mkdir "%BASE_PATH%\.github\workflows"

mkdir "%BASE_PATH%\docs"

mkdir "%BASE_PATH%\backend"
mkdir "%BASE_PATH%\backend\app"
mkdir "%BASE_PATH%\backend\app\Http"
mkdir "%BASE_PATH%\backend\app\Http\Controllers"
mkdir "%BASE_PATH%\backend\app\Http\Middleware"
mkdir "%BASE_PATH%\backend\app\Http\Resources"
mkdir "%BASE_PATH%\backend\app\Models"
mkdir "%BASE_PATH%\backend\app\Services"
mkdir "%BASE_PATH%\backend\config"
mkdir "%BASE_PATH%\backend\database"
mkdir "%BASE_PATH%\backend\database\migrations"
mkdir "%BASE_PATH%\backend\database\seeders"
mkdir "%BASE_PATH%\backend\public"
mkdir "%BASE_PATH%\backend\routes"
mkdir "%BASE_PATH%\backend\storage"
mkdir "%BASE_PATH%\backend\tests"

mkdir "%BASE_PATH%\frontend"
mkdir "%BASE_PATH%\frontend\public"
mkdir "%BASE_PATH%\frontend\src"
mkdir "%BASE_PATH%\frontend\src\assets"
mkdir "%BASE_PATH%\frontend\src\components"
mkdir "%BASE_PATH%\frontend\src\pages"
mkdir "%BASE_PATH%\frontend\src\services"
mkdir "%BASE_PATH%\frontend\src\store"
mkdir "%BASE_PATH%\frontend\src\styles"

mkdir "%BASE_PATH%\mobile"
mkdir "%BASE_PATH%\mobile\src"
mkdir "%BASE_PATH%\mobile\src\assets"
mkdir "%BASE_PATH%\mobile\src\components"
mkdir "%BASE_PATH%\mobile\src\screens"
mkdir "%BASE_PATH%\mobile\src\services"
mkdir "%BASE_PATH%\mobile\src\contexts"
mkdir "%BASE_PATH%\mobile\src\navigation"

mkdir "%BASE_PATH%\ai_models"
mkdir "%BASE_PATH%\ai_models\soluciobot_core"
mkdir "%BASE_PATH%\ai_models\soluciobot_core\models"
mkdir "%BASE_PATH%\ai_models\soluciobot_core\data"
mkdir "%BASE_PATH%\ai_models\soluciobot_core\scripts"

mkdir "%BASE_PATH%\database"
mkdir "%BASE_PATH%\database\migrations"
mkdir "%BASE_PATH%\database\seeders"
